dart-lang/tools

.github/workflows/publish.yaml
README.md
pkgs/dash_analytics/CHANGELOG.md
pkgs/dash_analytics/lib/src/constants.dart
pkgs/dash_analytics/pubspec.yaml

- contribute publishing automation
- dial `dash_analytics` back to a pre-release version until we're ready for the first publish

contribute publishing automation

---

README.md
pkgs/dash_analytics/README.md

- add some clarification to the top-level readme (mostly that this is intended to host tools.dart.dev packages)

add some clarification to the top-level readme

---

pkgs/dash_analytics/lib/src/config_handler.dart
pkgs/dash_analytics/test/dash_analytics_test.dart

We have recently decided to make sure that all tool labels are underscore delimited instead of hyphens. This PR fixes the regex pattern for the tool line in the config file. Sample of what a config file looks like is shown below with one tool initialized
```
#
#
#
#
reporting=1
#
#
#
#
flutter_tools=2023-02-22,1
```

Update to regex to look for underscore delimited labels

---

pkgs/unified_analytics/pubspec.yaml

Updating as hinted in the `dart pub publish --dry-run`
```
Resolving dependencies... 
_fe_analyzer_shared 54.0.0 (55.0.0 available)
analyzer 5.6.0 (5.7.1 available)
intl 0.17.0 (0.18.0 available)
Got dependencies!
Publishing unified_analytics 0.1.0-dev to https://pub.dev:
├── CHANGELOG.md (<1 KB)
├── LICENSE (1 KB)
├── README.md (<1 KB)
├── USAGE_GUIDE.md (5 KB)
├── analysis_options.yaml (1 KB)
├── coverage_runner.sh (<1 KB)
├── example
│   └── unified_analytics_example.dart (1 KB)
├── lib
│   ├── src
│   │   ├── analytics.dart (10 KB)
│   │   ├── config_handler.dart (7 KB)
│   │   ├── constants.dart (3 KB)
│   │   ├── enums.dart (2 KB)
│   │   ├── ga_client.dart (1 KB)
│   │   ├── initializer.dart (4 KB)
│   │   ├── log_handler.dart (8 KB)
│   │   ├── session.dart (3 KB)
│   │   ├── …
```

Update Dart sdk constraint in pubspec

---

.github/workflows/unified_analytics.yml

- related to https://github.com/dart-lang/setup-dart/issues/79 - switch this repo to use the `setup-dart` action from head (in order to dogfood the pre-release version of it)

dogfood the new version of the setup-dart action

---

pkgs/unified_analytics/lib/src/constants.dart

The messaging has been updated to reflect the correct commands for both `flutter` and `dart` cli tools for enabling and disabling telemetry.
This message can also be shown to users through the `Analytics` getter `toolsMessage`
```dart
abstract class Analytics {
/// Boolean that lets the client know if they should display the message
bool get shouldShowMessage;
/// Returns the message that should be displayed to the users if
/// [shouldShowMessage] returns true
String get toolsMessage;
}
```
The updated messaging is below
```
Flutter and Dart related tooling uses Google Analytics to report usage and
diagnostic data along with package dependencies, and crash reporting to
send basic crash reports. This data is used to help improve the Dart
platform, Flutter framework, and related tools. …
```

Update messaging for tools messaging

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/USAGE_GUIDE.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/log_handler.dart
pkgs/unified_analytics/lib/src/user_property.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

This update will include more information for the stats returns from the log file. The following keys have been added
`minsFromStartDateTime` – how many minutes have elapsed since the oldest log item
`minsFromEndDateTime` – how many minutes have elapsed since the earliest log item
`recordCount` – total count of records in the log file
`eventCount` – a map object that has each event sent as the key and a count of how many times that event was sent
```dart
{
"startDateTime": "2023-02-22 15:23:24.410921",
"minsFromStartDateTime": 20339,  // NEW
"endDateTime": "2023-03-08 15:46:36.318211",
"minsFromEndDateTime": 156,  // NEW
"sessionCount": 7,
"flutterChannelCount": 2,
"toolCount": 1,
"recordCount": 23,  // NEW
"eventCount": {  // NEW
"hot_reload_time": 16,
"analytics_collection_enabled": 7
} …
```

Adding more information to `LogFileStats` + minor updates to tests

---

.github/ISSUE_TEMPLATE/cli_config.md
.github/labeler.yml
.github/workflows/cli_config.yml
CODEOWNERS
README.md
pkgs/cli_config/.gitignore
pkgs/cli_config/CHANGELOG.md
pkgs/cli_config/LICENSE
pkgs/cli_config/README.md
pkgs/cli_config/analysis_options.yaml
pkgs/cli_config/lib/cli_config.dart
pkgs/cli_config/pubspec.yaml
pkgs/cli_config/test/cli_config_test.dart

Sets up the directory structure for `package:cli_config`.
The package contains no Dart code yet, this will be added later.

Empty package for `package:cli_config`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/USAGE_GUIDE.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml

Addresses: https://github.com/dart-lang/tools/issues/48
This new constructor will allow other developers using this package to test sending events to a test instance in Google Analytics.
Developers will need to request access to the BigQuery instance to see the data that is being exported

Analytics development constructor

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/USAGE_GUIDE.md
pkgs/unified_analytics/example/unified_analytics_example.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/test/unified_analytics_test.dart
pkgs/unified_analytics/test/workflow_test.dart

As discussed in the meeting, the following have been added to this PR to align with the PDD
1. Constants found in `constants.dart` have been aligned to match the PDD
2. Creation of static method to retrieve the consent message for a given `DashTool` without having to create an instance of `Analytics` – previously, you had to create an instance of the `Analytics` class to retrieve the message
Other various updates that remove unnecessary inputs for the analytics implementation constructor as well + documentation updates

Align to PDD

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/example/unified_analytics_example.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/config_handler.dart
pkgs/unified_analytics/test/workflow_test.dart

This PR is related to @jcollins-g comments about not incrementing the version number by 1. In the case the user has not updated for a while they would potentially have to see 4 different messages if they need to go from version 1 to 5.
With this PR, we will automatically use the version number that is passed to the constructor from the `constants.dart` file

Use version number for incrementing

---

pkgs/cli_config/lib/src/cli_source.dart
pkgs/cli_config/lib/src/config.dart
pkgs/cli_config/lib/src/environment_source.dart
pkgs/cli_config/lib/src/file_source.dart
pkgs/cli_config/lib/src/source.dart
pkgs/cli_config/test/cli_config_test.dart

Provide both optional and non-optional accessors for list config variables.
The non-optional accessors require at least one of the sources to provide at least an empty list. (For example JNIgen wants `classes` to be defined, even though it might be an empty list.)

[cli_config] Make string list and path list consistent

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/lib/src/log_handler.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/test/pdd_approved_test.dart
pkgs/unified_analytics/test/unified_analytics_test.dart

This PR will disable the creation of the two files that have yet to be approved in the privacy document
1. `dart-flutter-telemetry-session.json` 
2. `dart-flutter-telemetry.log`
Without the session json file, there will be no session data being sent to the Google Analytics backend. A session in this sense is at minimum 30 minutes, but if the user is active for a full hour, then the session will get extended. This requires persistence of state.
Without the log file, we simply won't be saving the data that is sent to Google Analytics on the user's machine. This blocks a feature necessary for sending user surveys based on a user's historical activity.
This PR introduces only a new constructor `Analytics.pddApproved(...)` so to make it easy to switch back to default constructor once the …

Disable unapproved files

---

pkgs/cli_config/lib/src/config.dart
pkgs/cli_config/test/cli_config_windows_test.dart

Apparently windows path resolving requires slightly different treatment.
The test in this CL fails with `Uri.resolve` but not with `Uri.resolveUri`.

Fix windows path resolving

---

pkgs/cli_config/CHANGELOG.md
pkgs/cli_config/lib/src/config.dart
pkgs/cli_config/lib/src/file_parser.dart
pkgs/cli_config/pubspec.yaml
pkgs/cli_config/test/cli_config_test.dart

YAML supports non-String map keys.
Our hierarchical key structure requires Strings as keys for maps, otherwise we can't get hierarchical access.
Give a proper error message on non-String keys.
Also, having null values in maps is useless as the config file is the last source. The value should then just be omitted.

[cli_config] Support non-String map keys

---

pkgs/unified_analytics/lib/src/analytics.dart

As part of https://github.com/dart-lang/tools/issues/70, initializing date formatting upstream within the package will ensure that clients using this package won't need to call it before implementing.
This package requires date formatting for the dates that are written and read from the config file that stores when each tool was onboarded to telemetry collection.

[unified_analytics] Initialize date formatting (package:intl requirement)

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml

In order for the analyzer to use the same consent protocol for crash reporting as the rest of the analytics, we have to know dynamically whether or not it is OK to send a crash report.   The `_clientShowedMessage` private variable has no getter so it is not possible to reproduce the same check that Analytics uses internally.  This small refactor adds a getter to provide a one-stop shop to check whether it is OK to send.

Add a `okToSend` getter to the Analytics class

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/analysis_options.yaml
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/ga_client.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/test/legacy_analytics_test.dart
pkgs/unified_analytics/test/unified_analytics_test.dart

Fixes https://github.com/dart-lang/tools/issues/74
Also addresses the consent message edit: https://github.com/dart-lang/tools/issues/82

Honor legacy opt out status

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/config_handler.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/no_op_analytics_test.dart
pkgs/unified_analytics/test/unified_analytics_test.dart
pkgs/unified_analytics/test/workflow_test.dart

Addresses tech debt issue:  https://github.com/dart-lang/tools/issues/17
Keeps the `dateStamp` string getter in one location instead of having static methods defined in two separate classes (tech debt)

Move `dateStamp` getter to `utils.dart`

---

pkgs/unified_analytics/lib/src/enums.dart

VS Code always uses the term "extensions" and not "plugins" so it looked slightly odd seeing "plugins" in the analytics prompt.
I only updated the description because I wasn't sure of the implications of changing "label" (particularly if the beta is already using the old value). As far as I can tell, although it's named "label" it's not user-facing?
FYI @eliasyishak @bwilkerson

Change "plugins" to "extensions" for VS Code

---

pkgs/unified_analytics/USAGE_GUIDE.md
pkgs/unified_analytics/example/unified_analytics_example.dart

Updating the usage guide to reflect the changes from the PDD discussion. This update shows developers using this package how to properly:
1. Check if the consent message needs to be shown
2. How to get the consent message from the `Analytics` instance
3. How to confirm that the message has been shown and officially onboard the user into analytics collection
Addresses issue: https://github.com/dart-lang/tools/issues/63

Update usage guide for onboarding users

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/test/survey_handler_test.dart

Tracker issue:
For our users that have opted out of telemetry collection, we should prevent any surveys from getting sent to them.
--- …

No surveys for opted out users

---

.github/workflows/graphs.yml
pkgs/graphs/.gitignore
pkgs/graphs/CHANGELOG.md
pkgs/graphs/CONTRIBUTING.md
pkgs/graphs/LICENSE
pkgs/graphs/README.md
pkgs/graphs/analysis_options.yaml
pkgs/graphs/benchmark/connected_components_benchmark.dart
pkgs/graphs/benchmark/shortest_path_benchmark.dart
pkgs/graphs/benchmark/shortest_path_worst_case_benchmark.dart
pkgs/graphs/example/crawl_async_example.dart
pkgs/graphs/example/example.dart
pkgs/graphs/lib/graphs.dart
pkgs/graphs/lib/src/crawl_async.dart
pkgs/graphs/lib/src/cycle_exception.dart
pkgs/graphs/lib/src/shortest_path.dart
pkgs/graphs/lib/src/strongly_connected_components.dart
pkgs/graphs/lib/src/topological_sort.dart
pkgs/graphs/lib/src/transitive_closure.dart
pkgs/graphs/pubspec.yaml
pkgs/graphs/test/crawl_async_test.dart
pkgs/graphs/test/shortest_path_test.dart
pkgs/graphs/test/strongly_connected_components_test.dart
pkgs/graphs/test/topological_sort_test.dart
pkgs/graphs/test/transitive_closure_test.dart
pkgs/graphs/test/utils/graph.dart
pkgs/graphs/test/utils/utils.dart

_Do NOT squash merge!_
Reasons for merging into dart-lang/tools mono_repo:
* Easier maintenance.
* Automatic mirroring in https://dart.googlesource.com/tools instead of setting up a new mirror for graphs.
Steps taken:
1. Get git-filter-repo: \
`newren $ git clone git@github.com:newren/git-filter-repo.git`
2. Add `git-filter-repo` to `PATH`.
3. Fresh clone of repo that needs to be merged into a mono repo: \
`dart-lang $ git clone git@github.com:dart-lang/graphs.git`
4. Destructively rewrite the history of the repository to be in `pkgs/package_name`: \
`graphs $ git filter-repo --path-rename :pkgs/graphs/`
5. Destructively prefix all the tags: \
`graphs $ git filter-repo --tag-rename :graphs-`
6. Replace paths and links in files.
1. Badges: …

Merge graphs package

---

.github/workflows/pull_request_label.yml
pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/example/unified_analytics_example.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/asserts.dart
pkgs/unified_analytics/test/asserts_test.dart

Addresses:
- https://github.com/dart-lang/tools/issues/94
Asserts added (and can be turned on from factory constructors) to check against GA4 limitations. By default `Analytics()` constructor will have asserts disabled and the `Analytics.development()` constructor will have them enabled
---
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package …

Asserts added to check all relevant GA4 limitations

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/example/unified_analytics_example.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/no_op_analytics_test.dart

Addresses issue:
- https://github.com/dart-lang/tools/issues/93
Issue filed in the `flutter/flutter` repo:
- https://github.com/flutter/flutter/issues/127055
This makes use of the `Directory`'s `statSync()` method along with the `modeString()` method on `FileStat` to return the permissions set on a given directory and checks for write permissions. If there are no permissions to write to a user's home directory, the factory constructor will return a NoOp implementation
---
- Contributions to our repos should follow the [Dart style …

Utility function added to check permissions on directory

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/suppression_test.dart

Addresses issue:
- https://github.com/dart-lang/tools/issues/124
This feature allows us to call a method on the analytics instance and suppress any events from being sent for the current invocation. This will allow clients of this tool such as the flutter-tool to simply call the method for a given command such as `flutter --suppress-analytics`
---
<details>
- Most changes should add an entry to …

Suppress telemetry feature

---

pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/survey_handler.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/test/survey_handler_test.dart

This addresses part of the umbrella issue:
This feature adds a utility function that can take two different strings and return a decimal value that we can compare against the sampling rate found in the remotely hosted metadata survey file (sample below)
```json
[
{
"uniqueId": "test_channel",
"url": "https://google.qualtrics.com/jfe/form/SV_5gsB2EuG5Et5Yy2",
"startDate": "2023-06-01T09:00:00-07:00",
"endDate": "2023-06-30T09:00:00-07:00",
"description": "Help improve Flutter's release builds with this 3-question survey!",
"dismissForDays": "10",
"moreInfoURL": "https://docs.flutter.dev/reference/crash-reporting",
"samplingRate": "0.1",    <---- the newly generated decimal value will be compared against value
"conditions": [
{
"field": …
```

Sampling rate functionality added

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/lib/src/log_handler.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/lib/src/survey_handler.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/test/survey_handler_test.dart
pkgs/unified_analytics/test/unified_analytics_test.dart
pkgs/unified_analytics/test/workflow_test.dart

This feature will add the ability to dismiss a survey and have its unique id be persisted locally on disk so that it doesn't get prompted again to the user.  A dismissal occurs if the user chooses to open the survey or dismiss it without completing it
Address umbrella issue:
Example of usage
```dart
// This will grab any available surveys from the remote host and apply
// the sampling rate (if applicable for that survey) and check that the
// the surveys available have not been dismissed or snoozed
final surveyList = analytics.fetchAvailableSurveys();
if (surveyList.length > 0) {
// Recommended to take the first item in the list since
// there could be multiple surveys available
final survey = surveyList.first;
// pseudo-code to simulate …
```

Dismissing and persisting surveys

---

pkgs/unified_analytics/lib/src/ga_client.dart

Fix #131 
The `Response` in http package uses `content-type` in response header to infer the encoding for its body. However, the header is not specified in this fake response and latin1 will be used as fallback, which cannot encode non-latin letters.
In this pr, a proper header is added and `utf-8` will be used to encode response body.
---
<details>
- Most changes should add an entry to the …

Fix crash caused by response encoding for GAClient

---

pkgs/unified_analytics/example/sample_rate.dart
pkgs/unified_analytics/example/serving_surveys.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/lib/src/survey_handler.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/lib/unified_analytics.dart
pkgs/unified_analytics/test/events_with_fake_test.dart
pkgs/unified_analytics/test/survey_handler_test.dart

Reference issue:
With the new update to the json to include a button array, this PR includes a new class that will be generated for each button that is listed with a given survey
Example of the json update
```json
[
{
"uniqueId": "eca0100a-505b-4539-96d0-57235f816cef",
"startDate": "2023-07-01T09:00:00-07:00",
"endDate": "2023-08-31T09:00:00-07:00",
"description": "Help improve Flutter's release builds with this 3-question survey!",
"snoozeForMinutes": "7200",
"samplingRate": "0.1",
"conditions": [
{
"field": "logFileStats.recordCount",
"operator": ">=",
"value": 1000
}
],
// Newly added key in json that contains button info
"buttons": [
{
"buttonText": "Take Survey",
"action": "accept",
"url": …
```

Refactor for buttons array with `SurveyButton` class

---

pkgs/cli_config/CHANGELOG.md
pkgs/cli_config/README.md
pkgs/cli_config/example/pubspec.yaml
pkgs/cli_config/pubspec.yaml

-add usage docs to package:cli_config
Not included in this PR, but it may also be useful to provide examples around env var + config file usage.
---
<details> …

add usage docs to package:cli_config

---

pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/asserts.dart
pkgs/unified_analytics/lib/src/config_handler.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/lib/src/ga_client.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/lib/src/log_handler.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/lib/src/survey_handler.dart
pkgs/unified_analytics/lib/src/user_property.dart
pkgs/unified_analytics/lib/src/utils.dart

Fixes:
- https://github.com/dart-lang/tools/issues/126
Address [comment](https://github.com/dart-lang/tools/pull/109#discussion_r1282358404) to ensure docs follow style guide
[effective-dart style guide](https://dart.dev/effective-dart/documentation)
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …

Clean up on dart docs across all dart files under lib

---

pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart

Required for migration of Dart CLI and dart-lang/pub from `package:usage` to `package:unified_analytics`.

Added `dartCliCommandExecuted` and `pubGet` events

---

pkgs/extension_discovery/CHANGELOG.md
pkgs/extension_discovery/lib/src/expect_json.dart
pkgs/extension_discovery/pubspec.yaml

While debugging https://github.com/dart-lang/tools/issues/146, I found that the error messages needed to be more specific. This `FormatException`s will now include the name of the "key" that has an invalid value, and the map it is a part of.  This should save considerable time for debugging future format errors.

Improve exception messages for `ExpectJson` extension

---

pkgs/extension_discovery/CHANGELOG.md
pkgs/extension_discovery/lib/src/expect_json.dart
pkgs/extension_discovery/lib/src/package_config.dart
pkgs/extension_discovery/pubspec.yaml
pkgs/extension_discovery/test/package_config_test.dart

Ensure that we support cases where `packageUri` is not present.
Fixes https://github.com/dart-lang/tools/issues/146

Support optional packageUri

---

pkgs/unified_analytics/lib/unified_analytics.dart

I think this is just an oversight (and not deliberate). Without it, I can't use `Survey` explicitly in code without importing from `src`.
@eliasyishak

Export Survey in package:unified_analytics

---

pkgs/extension_discovery/CHANGELOG.md
pkgs/extension_discovery/README.md
pkgs/extension_discovery/example/hello_world/lib/hello_world.dart
pkgs/extension_discovery/example/hello_world_german/extension/hello_world/config.json
pkgs/extension_discovery/example/hello_world_german/extension/hello_world/config.yaml
pkgs/extension_discovery/lib/extension_discovery.dart
pkgs/extension_discovery/lib/src/expect_json.dart
pkgs/extension_discovery/lib/src/registry.dart
pkgs/extension_discovery/lib/src/yaml_config_format.dart
pkgs/extension_discovery/pubspec.yaml
pkgs/extension_discovery/test/find_extensions_test.dart
pkgs/extension_discovery/test/integration_test.dart
pkgs/extension_discovery/test/yaml_config_format_test.dart

* Changed `config.json` to `config.yaml` for consistency with other tooling.
* Added robustness checks on YAML to ensure:
* Root is a map,
* Config can be serialized as JSON,
* We don't leak YamlNode subtypes out of the API for this package
(keeping YAML an implementation detail from the perspective of a consumer of this package).
* Tweaked the cache format (bumped the version number)
* Bumped package version number to 2.0.0
* Added a few more tests :rocket: 
Fixes https://github.com/dart-lang/tools/issues/152

Extension discovery 2.0.0

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/no_op_analytics_test.dart

Fixes:
- https://github.com/dart-lang/tools/issues/162
---
<details>
Note that many …

Expose the client id + hard code for NoOp instance

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/example/unified_analytics_example.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml

Using constant for no op client id so that it can also be referenced in client tests (ie. flutter-tool tests)
---
<details> …

Use constant for no op client id

---

pkgs/extension_discovery/CHANGELOG.md
pkgs/extension_discovery/analysis_options.yaml
pkgs/extension_discovery/lib/src/expect_json.dart
pkgs/extension_discovery/lib/src/io.dart
pkgs/extension_discovery/lib/src/package_config.dart
pkgs/extension_discovery/lib/src/registry.dart
pkgs/extension_discovery/lib/src/yaml_config_format.dart
pkgs/extension_discovery/pubspec.yaml
pkgs/extension_discovery/test/find_extensions_test.dart
pkgs/extension_discovery/test/test_descriptor.dart
pkgs/extension_discovery/test/yaml_config_format_test.dart

- update to the latest package:dart_flutter_team_lints
---
<details>
Note that many …

update to the latest package:dart_flutter_team_lints

---

pkgs/unified_analytics/lib/src/asserts.dart
pkgs/unified_analytics/test/asserts_test.dart

In my testing in the flutter tool codebase, I realized that adding more info about what was causing the failure when enabling asserts would be beneficial to others working with this package and other clients of this package.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Main …

Add more info into the `AnalyticsException`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/example/unified_analytics_example.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/log_handler_test.dart
pkgs/unified_analytics/test/suppression_test.dart
pkgs/unified_analytics/test/survey_handler_test.dart

Related to issue:
- https://github.com/dart-lang/tools/issues/183
This PR is adding an internal instance member `_futures`, which is a list of `Future` objects that are returned from the http client.
When the user of this package invokes `analytics.send(...)`, they will no longer have to `await` the call which can delay them. However, at the end, the user of this package should call `analytics.close()` and `await` that call on exit to ensure events have been sent.
---
<details>
- Contributions to our repos should follow the [Dart …

Use futures list internally to manage send events

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

- Part of: https://github.com/flutter/flutter/issues/128251
As part of the migration for `flutter doctor` events, this PR introduces the new enum and Event constructors for the doctor related events
Using this event, we can create a query to check how validator results change over time, sample query below
Additionally, with the `doctorInvocationId` being used to aggregate data across multiple doctor validators, we can get a percentage of validators that returned `success` in one invocation. (ie. there was 9 validators that returned success out of 10, so we can calculate 90% of successes for that invocation)
The above shows the average of all percent successes for a given week for all users.
---
<details>
- See our [contributor …

Enum + event constructors added for doctor events

---

pkgs/unified_analytics/test/event_test.dart

Closes issue:
- https://github.com/dart-lang/tools/issues/182
---
<details>
Note that …

Create tests for each event constructor

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

Related to issue:
Migrating the `BuildEvent` from `package:usage` to `package:unified_analytics`
Snippet of the code for `BuildEvent`
```dart
class BuildEvent extends UsageEvent {
BuildEvent(String label, {
String? command,
String? settings,
String? eventError,
required Usage flutterUsage,
required String type,
}) : _command = command,
_settings = settings,
_eventError = eventError,
super(
// category
'build',
// parameter
type,
label: label,
flutterUsage: flutterUsage,
);
final String? _command;
final String? _settings;
final String? _eventError;
@override
void send() {
final CustomDimensions parameters = CustomDimensions(
buildEventCommand: _command,
buildEventSettings: _settings,
buildEventError: _eventError,
);
flutterUsage.sendEvent( …
```

Enum + event constructors added for build events

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

PR in `flutter/flutter` implementing this new `Event`:
- https://github.com/flutter/flutter/pull/137717
---
<details>
- Changes to …

Added new event enum + constructor for hot runner

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/test/event_test.dart

Part of tracker issue:
Intended to be the replacement for [`CommandResultEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L191-L193) from legacy analytics in `flutter/flutter`
There is only one place within the flutter-tool that we call the `CommandResultEvent.send` method and it is [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart#L1592-L1600)
---
<details>
- …

Enum + event constructor added for `flutterCommandResult`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

This migrates the `CodeSizeEvent` event, which is defined [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L236-L244) and below
```dart
/// An event that reports when the code size measurement is run via `--analyze-size`.
class CodeSizeEvent extends UsageEvent {
CodeSizeEvent(String platform, {
required Usage flutterUsage,
}) : super(
'code-size-analysis',
platform,
flutterUsage: flutterUsage
);
}
```
There is only one reference of this class getting called within the flutter tool code base and it is within [`flutter_tools/lib/src/base/analyze_size.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/analyze_size.dart#L9 …

Add enum + event constructor for code size analysis

---

pkgs/cli_config/analysis_options.yaml
pkgs/graphs/analysis_options.yaml
pkgs/unified_analytics/analysis_options.yaml

- remove duplicate settings from analysis_options files
---
<details>
Note that many …

remove duplicate settings from analysis_options files

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

Closes:
- https://github.com/dart-lang/tools/issues/197
While migrating the `Usage.command` static method, includes the `commandHasTerminal` parameter, I realized that it probably makes sense to include it with the previously migrated `CommandResult` event.
This new event will now let us record which flutter command was run, while also keeping track of whether the invocation included a terminal.
---
<details>
- Contributions to our repos should follow the …

Add terminal info to flutter command event

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

This PR adds 2 events here, one for the generic `UsageEvent` in flutter, and another for the `sendException` method in flutter.
For the `UsageEvent`, you can refer to this [sheet](https://docs.google.com/spreadsheets/d/11KJLkHXFpECMX7tw-trNkYSr5MHDG15XNGv6TgLjfQs/edit?usp=sharing&resourcekey=0-j4qdvsOEEg3wQW79YlY1-g) which shows all the call sites for that event. I found that all of these events were apple related so I consolidated them down into just one event. The event created for is called `Event.appleUsageEvent`
For the `sendException` method, we are only sending the exception's runtimeType as a string from flutter, so i created the `Event.exception` constructor which takes just one parameter for the …

Add generic usage event used for iOS/macOS workflows + generic `exception` event

---

pkgs/extension_discovery/pubspec.yaml

An explicit dep on `pkg:lints` is not needed.
---
<details>
Note that many Dart repos …

[extension_discovery] Drop unneeded dependency on pkg:lints

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

This PR adds a general timing event that can be used by any client of `package:unified_analytics`. The fields in the `Event` constructor for this event have been designed to match what was used for the `sendTiming` method in [`flutter/flutter`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/usage.dart#L295-L311)
```dart
@override
void sendTiming(
String category,
String variableName,
Duration duration, {
String? label,
}) {
if (suppressAnalytics) {
return;
}
_analytics.sendTiming(
variableName,
duration.inMilliseconds,
category: category,
label: label,
);
}
```
---
<details>
- See our [contributor …

Added enum + event for timing events

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

This is a migration for the flutter `Usage.command` static method. When calling this method from `FlutterCommand` or a child class, it will fetch the necessary `CustomDimensions` for that command. There are a few child classes of `FlutterCommand` that override the `usageValues` getter to provide their own custom dimensions.
As a result, this means that parameters we need to send for each of those classes varies. So instead of creating a separate `Event` constructor for each of these child classes, we will instead have just one constructor that contains a superset of all possible custom dimension parameters. This makes the parameter count for this `Event` large (even larger than the maximum 25 parameters allowed). …

Enum + event added for `commandUsageValues`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/example/unified_analytics_example.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/user_property.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

Closes:
- https://github.com/dart-lang/tools/issues/198
The main change for this PR will add a new optional field on the `Analytics` constructors to allow sending a string for the enabled features.
From the example file below
```dart
final Analytics analytics = Analytics.development(
tool: DashTool.flutterTool,
flutterChannel: 'ey-test-channel',
flutterVersion: 'Flutter 3.6.0-7.0.pre.47',
clientIde: 'VSCode',
dartVersion: 'Dart 2.19.0',
// This can be set to true while testing to validate
// against GA4 usage limitations (character limits, etc.)
enableAsserts: false,
enabledFeatures: 'feature-1,feature-2',  // <---- the newly added parameter
);
```
The string indicating the enabled features will be sent with every event in the user properties. This is similar to what we did before in …

Add `enabledFeatures` key to `Analytics` constructors

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/legacy_analytics_test.dart

This PR will make sure that when the config file for `package:unified_analytics` is being created the first time, it will check in the devtools config file for previous opt out status. If the user has already opted out in the past but haven't interacted with `package:unified_analytics` yet, then it will pass that information and opt out the user from `package:unified_analytics` collection.
---
<details>
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart …

Checking for devtools config file for opt out

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/lib/unified_analytics.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

This PR provides a helper method that can be used by clients of package:unified_analytics to resolve the dart sdk version from the `Platform.version` string provided by `dart:io`.
Additional parsing is necessary because we want to remove the extra information that is returned from this string.
```
Original from Platform.version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "macos_arm64"
After parsing with helper:      3.3.0
```
The above is for dart sdks on the stable channel, the below is for non-stable
```
Original from Platform.version: 2.1.0-dev.8.0.flutter-312ae32
After parsing with helper:      2.1.0 (build 2.1.0-dev.8.0 312ae32)
```
The logic for this regex was borrowed from the logic that exists within the flutter/flutter repo …

Helper to resolve dart version for clients of analytics

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/pubspec.yaml

Fixes:
- https://github.com/flutter/flutter/issues/143792
This PR changes the error handling behavior when attempting to parse the json file for session data. Instead of trying to parse the newly created file, it will set the current session to the current datetime. This is possibly a race condition issue that will be investigated further in the below issue.
- https://github.com/dart-lang/tools/issues/166
---
<details>
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) …

Fallback to current datetime when failing on parse session json file

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/pubspec.yaml

Fixes:
- https://github.com/flutter/flutter/issues/143792
This PR changes the error handling behavior when attempting to parse the json file for session data. Instead of trying to parse the newly created file, it will set the current session to the current datetime. This is possibly a race condition issue that will be investigated further in the below issue.
- https://github.com/dart-lang/tools/issues/166
---
<details>
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) …

`5.8.0+1` package:unified_analytics hotfix for `5.8.0`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/testing.dart
pkgs/unified_analytics/pubspec.yaml

Fixes:
- #234 
To fix lint `implementation_imports` in flutter/flutter
---
<details> …

Export `testing.dart` with all enums

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

Fixes:
- https://github.com/dart-lang/tools/issues/238
TLDR: initialization logic within the `Session` class's constructor body expects `Analytics.userProperty` to be initialized, this moves that constructor body logic from `Session` into a separate method (`Session.initialize`) we will call at the end of the `Analytics` class's constructor after we are sure all necessary fields have been initialized
---
<details>
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and …

Fix late initialization error for `Analytics.userProperty`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

Fixes:
- https://github.com/dart-lang/tools/issues/240
Related to:
- https://github.com/dart-lang/tools/issues/166
This update makes it so that we only write to the session file only when the session id needs to be updated. Previously, we were writing with every event in order to keep track of when the last ping was so that we can keep the session alive or start a new one.
We now instead use the last modified timestamp for the session file as a stand in for when the last ping happened.
The file's format has also changed
```jsonc
// OLD
{"session_id": 123, "last_ping": 123}
// NEW
{"session_id": 123}
```
---
<details>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for …

Limit writes to session file

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml

For fix upstream bug:
- https://github.com/flutter/flutter/issues/139861
---
<details> …

Bump version for 5.8.6

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/initializer.dart
pkgs/unified_analytics/lib/src/session.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
- …

Update other session file create callsite

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/example/serving_surveys.dart
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/test/error_handler_test.dart
pkgs/unified_analytics/test/events_with_fake_test.dart
pkgs/unified_analytics/test/legacy_analytics_test.dart
pkgs/unified_analytics/test/log_handler_test.dart
pkgs/unified_analytics/test/suppression_test.dart
pkgs/unified_analytics/test/survey_handler_test.dart
pkgs/unified_analytics/test/unified_analytics_test.dart
pkgs/unified_analytics/test/workflow_test.dart

This PR swaps out the `Analytics.test` factory constructor for static method `Analytics.fake`. 
---
<details> …

Use static method for fake instance

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml

Bump version to 6.0.0

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/README.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/error_handler_test.dart
pkgs/unified_analytics/test/log_handler_test.dart

Proactive fix for:
- https://github.com/flutter/flutter/issues/146153
---
<details> …

Hotfix analytics `5.8.8+1`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

Part of tracker issue:
- https://github.com/flutter/devtools/issues/7083
Devtools uses one large data class for all of their events. This PR is adding that data class as a named constructor under `Event` called `Event.devtoolsAction`
The singular data class can be found [here in devtools source code](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/shared/analytics/_analytics_web.dart#L52-L112).
---
<details>
- Contributions to our repos should follow the [Dart style …

`Event` Constructor added for devtools event

---

.github/workflows/cli_config.yml

Don't collect coverage on Windows

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/log_handler.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/log_handler_test.dart

Addresses https://github.com/flutter/flutter/issues/150137
---
<details> …

delete old log file if it exceeds kMaxLogFileSize of 25MiB

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/log_handler.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/log_handler_test.dart

The goal of this is to patch unified_analytics v5 with the fixes from https://github.com/dart-lang/tools/pull/274 and https://github.com/dart-lang/tools/pull/277.
In summary, unified_analytics logs (the 2500 most-recent) outgoing analytics events. This is primarily to be read in the future for targeted surveys. However, due to some unknown edge case(s) (investigation pending), it's possible [this file can reach a massive size](https://github.com/flutter/flutter/issues/150137#issuecomment-2166921874). #277 fixed this for unified_analytics v6, but we need to port this to v5, because the stable branch of Flutter (which we want to hotfix) uses v5.
---
<details>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUT …

[unified_analytics 5.8.8] Prevent `FileSystemException`s from happening when logging outgoing events

---

.github/workflows/cli_config.yml
.github/workflows/unified_analytics.yml
pkgs/unified_analytics/lib/src/log_handler.dart
pkgs/unified_analytics/test/log_handler_test.dart

This is a follow-up to https://github.com/dart-lang/tools/pull/280. Basically, that PR cherry-picked some fixes from main (unified_analytics v6) to a new branch meant to eventually be published as unified_analytics v5.8.8+2. However, since there were some API changes in v6, the tests didn't work (I already remembered to verify the tests right after I merged 😛).
This PR patches these tests. It makes `LogHandler::logFile` writable via a `@visibleForTestingOnly` setter, which I think is okay for patching an old major version.
---
<details>
- Larger or significant changes should be discussed in an issue before creating …

Patch tests for unified_analytics 5.8.8+2 fixes

---

CODEOWNERS

- Update the CODEOWNERS file for package:unified_analytics
@andrewkolos, are you or @christopherfujino the best owner(s) for this package?
---
<details> …

Update CODEOWNERS for package:unified_analytics

---

.github/workflows/health.yaml
.github/workflows/post_summaries.yaml
pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/testing.dart

Add the PR health workflow and fix a missing license.
---
<details>
Note …

Add health workflow

---

pkgs/graphs/CHANGELOG.md
pkgs/graphs/README.md
pkgs/graphs/pubspec.yaml

Closes #103
Reword most of the README.
- Use "callback" consistently to describe the arguments to the
algorithms.
- Add generics and more specific names to the tiny example data
structures.
- Use consistent phrasing in the bullet points about the types of
callbacks needed.
- Reorder the bullet points since the edges callbacks are always used
and worth mentioning first.
Add a code block with skeleton examples of calls using each of the
example data structures. One example of calls `shortestPath` on a graph
with adjacency lists stored in a `Map` using terms related to
networking. The other calls `topologicalSort` on a graph represented by
a tree of node objects which store outgoing edges using terms related to
build dependencies.

Add examples of calling two algorithms to README

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/config_handler.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml

As I assume the datetime strings need not be localized. If they should be, then ignore this PR, and we should change the documentation instead.
---
<details>
- Changes to packages require …

Remove dependency on `package:intl`

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

Devtool PR: https://github.com/flutter/devtools/pull/8177
---
<details> …

Add more parameters (androidAppId and iosBundleId) in devtools events. 

---

pkgs/file/CHANGELOG.md
pkgs/file/pubspec.yaml
pkgs/file_testing/CHANGELOG.md
pkgs/file_testing/README.md
pkgs/file_testing/pubspec.yaml

- rev `package:file` and `package:file_testing` versions in prep for publishing
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIB …

rev package:file and package:file_testing versions in prep for publishing

---

pkgs/file_testing/CHANGELOG.md
pkgs/file_testing/lib/file_testing.dart
pkgs/file_testing/pubspec.yaml

- require dart 3.1; update to the latest lints
---
<details>
Note that …

require dart 3.1; update to the latest lints

---

pkgs/file/lib/src/interface/file_system.dart

These backticks break the references.
---
<details>
Note that many Dart …

Fix doc comment references with backticks

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

This was preventing data from getting sent properly to analytics.

Remove any `data` entries with a null value in the `Event.exception` constructor.

---

pkgs/coverage/CHANGELOG.md
pkgs/coverage/lib/src/isolate_paused_listener.dart
pkgs/coverage/pubspec.yaml
pkgs/coverage/test/isolate_paused_listener_test.dart

The sequence of events that reproduces the bug is:
1. Main isolate starts
2. Main isolate spawns other isolates
3. Other isolates pause, are collected, and exit
4. `IsolatePausedListener._allNonMainIsolatesExited` is completed, so `IsolatePausedListener.waitUntilAllExited` starts waiting on `IsolatePausedListener._mainIsolatePaused`.
5. Main isolate spawns more isolates
6. Main isolate pauses
7. `IsolatePausedListener._mainIsolatePaused` is completed, so `IsolatePausedListener.waitUntilAllExited` collects and resumes the main isolate
8. The main isolate has exited, so the VM shuts down, and the VM service connection is disposed
10. The remaining isolates pause, so `IsolatePausedListener` tries to collect and resume them, causing the exception seen in the bug.
Step 5 is the bit I didn't …

[coverage] Fix isolate resumption after service disposal

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

Fixes https://github.com/dart-lang/tools/issues/1195
---
<details>
Note …

In the `Event.exception` constructor, modify a clone of the `args` argument instead of `args` itself

---

pkgs/file/pubspec.yaml
pkgs/file_testing/CHANGELOG.md
pkgs/file_testing/analysis_options.yaml
pkgs/file_testing/lib/src/testing/core_matchers.dart
pkgs/file_testing/pubspec.yaml

And change the public signature to allow better reuse

Migrate many custom matchers to TypeMatcher

---

.github/workflows/bazel_worker.yaml
pkgs/bazel_worker/benchmark/benchmark.dart
pkgs/bazel_worker/e2e_test/bin/async_worker_in_isolate.dart
pkgs/bazel_worker/e2e_test/lib/async_worker.dart
pkgs/bazel_worker/e2e_test/lib/forwards_to_isolate_async_worker.dart
pkgs/bazel_worker/e2e_test/pubspec.yaml
pkgs/bazel_worker/e2e_test/test/e2e_test.dart
pkgs/bazel_worker/example/client.dart
pkgs/bazel_worker/lib/src/async_message_grouper.dart
pkgs/bazel_worker/lib/src/driver/driver.dart
pkgs/bazel_worker/lib/src/driver/driver_connection.dart
pkgs/bazel_worker/lib/src/message_grouper_state.dart
pkgs/bazel_worker/lib/src/utils.dart
pkgs/bazel_worker/lib/src/worker/async_worker_loop.dart
pkgs/bazel_worker/lib/src/worker/sync_worker_loop.dart
pkgs/bazel_worker/lib/src/worker/worker_connection.dart
pkgs/bazel_worker/lib/testing.dart
pkgs/bazel_worker/test/driver_test.dart
pkgs/bazel_worker/test/message_grouper_test.dart
pkgs/bazel_worker/test/worker_loop_test.dart
pkgs/clock/analysis_options.yaml
pkgs/coverage/analysis_options.yaml
pkgs/test_reflective_loader/pubspec.yaml

Remove duplicate lints in files

Bump dart_flutter_team lints to latest across packages

---

.github/ISSUE_TEMPLATE/string_scanner.md
pkgs/string_scanner/.github/dependabot.yml
pkgs/string_scanner/.github/workflows/publish.yaml
pkgs/string_scanner/.github/workflows/test-package.yml
pkgs/string_scanner/.gitignore
pkgs/string_scanner/CHANGELOG.md
pkgs/string_scanner/LICENSE
pkgs/string_scanner/README.md
pkgs/string_scanner/analysis_options.yaml
pkgs/string_scanner/example/example.dart
pkgs/string_scanner/lib/src/charcode.dart
pkgs/string_scanner/lib/src/eager_span_scanner.dart
pkgs/string_scanner/lib/src/exception.dart
pkgs/string_scanner/lib/src/line_scanner.dart
pkgs/string_scanner/lib/src/relative_span_scanner.dart
pkgs/string_scanner/lib/src/span_scanner.dart
pkgs/string_scanner/lib/src/string_scanner.dart
pkgs/string_scanner/lib/src/utils.dart
pkgs/string_scanner/lib/string_scanner.dart
pkgs/string_scanner/pubspec.yaml
pkgs/string_scanner/test/error_test.dart
pkgs/string_scanner/test/line_scanner_test.dart
pkgs/string_scanner/test/span_scanner_test.dart
pkgs/string_scanner/test/string_scanner_test.dart
pkgs/string_scanner/test/utils.dart

```
* Move to `dart-lang/tools` monorepo.
```
```
| [string_scanner](pkgs/string_scanner/) | A class for parsing strings using a sequence of patterns. | [![package issues](https://img.shields.io/badge/package:string_scanner-4774bc)](https://github.com/dart-lang/tools/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Astring_scanner) | [![pub package](https://img.shields.io/pub/v/string_scanner.svg)](https://pub.dev/packages/string_scanner) |
```
```
> [!IMPORTANT]  
> This repo has moved to https://github.com/dart-lang/tools/tree/main/pkgs/string_scanner
```
```
git tag --list 'string_scanner*' | xargs git push origin
```
```
Closing as the [dart-lang/string_scanner](https://github.com/dart-lang/string_scanner) repository is merged into the …
```

Merge `package:string_scanner`

---

pkgs/pubspec_parse/CHANGELOG.md
pkgs/pubspec_parse/lib/src/pubspec.dart
pkgs/pubspec_parse/lib/src/pubspec.g.dart
pkgs/pubspec_parse/pubspec.yaml
pkgs/pubspec_parse/test/parse_test.dart

Fixes #1814 by adding `Pubspec.workspace` (`List<String>?`) and `Pubspec.resolution` (`String?`). Didn't bump the changelog or version yet because I didn't want to conflict with #1946 (@kevmoo?), but I can do that once it's merged (or rebase this onto that branch). 
Does not check that `dart: ^3.6.0`, leaving that up to [these lines in Pub](https://github.com/dart-lang/pub/blob/58de642dc1d07601f6eb2b4ecd94555c0210106b/lib/src/pubspec.dart#L110-L122). 
An omitted `resolution:` or `workspace` field is treated as null. 
---
<details> …

Added `workspace:` and `resolution: fields`

---

pkgs/io/test/copy_path_test.dart

The current tests have no useful validation and pass even if the methods
under test are empty because they check that a directory is the same as
itself.
Add a directory name argument when creating the test descriptor
directory and use the parent and copy directory name for `_create` and
`_validate` respectively. Add constants for the directory names.

Fix check for copied directories

---

.github/workflows/deploy_pages.yaml
.github/workflows/markdown.yaml
.github/workflows/markdown_crash_test.yaml
.github/workflows/markdown_playground.yaml
.gitignore
pkgs/markdown/.gitignore
pkgs/markdown/CHANGELOG.md
pkgs/markdown/README.md
pkgs/markdown/lib/src/version.dart
pkgs/markdown/pubspec.yaml

- add a workflow to deply the markdown playground
- close https://github.com/dart-lang/tools/issues/1960
This deploys the markdown playground to https://dart-lang.github.io/tools on pushes to `main`, and tests that the app builds on every PR.
I may follow this up with a change that instead deploys to `https://dart-lang.github.io/tools/markdown` / `https://dart-lang.github.io/tools/markdown_playground` (or, happy to do that as part of this PR).
---
<details>
- Contributions to our repos should follow the [Dart style …

add a workflow to deply the markdown playground

---

pkgs/sse/CHANGELOG.md
pkgs/sse/test/sse_test.dart

Skipping a fail that is failing. See https://github.com/dart-lang/tools/issues/2006 for more details

skipping failing test

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/lib/src/user_property.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

Fixes https://github.com/flutter/flutter/issues/147327.
**Summary.** The `Analytics` constructor accepts a list of "enabled features" for the current user of the whatever tool is in use ([src](https://github.com/dart-lang/tools/blob/3934675f1595ed2fee2297d7d1cc96beaaa50c9e/pkgs/unified_analytics/lib/src/analytics.dart#L39-L42)). For example, in the Flutter tool, this will be a comma-delimited list of `flutter config` items set to `true` (explicitly by the user). When any event is sent off to Google Analytics, this list will be included as a _user property_ with the key "enabled_features".
See the parent issue. This list is prone to getting truncated due to the low character limit of user property values. This PR instead sends them as event properties. This has a _much_ higher character …

[unified_analytics] Send `enabled_features` as an event parameter rather than a user property

---

pkgs/pub_semver/CHANGELOG.md
pkgs/pub_semver/lib/src/version.dart
pkgs/pub_semver/pubspec.yaml

Use the `final` class modifier on `Version` instead of `@sealed`. This could technically break anyone who overrides the class while ignoring the resulting diagnostic from `@sealed`.

[pub_semver] Remove dependency on `package:meta`

---

pkgs/html/CHANGELOG.md
pkgs/html/lib/dom.dart
pkgs/html/lib/src/tokenizer.dart
pkgs/html/pubspec.yaml
pkgs/html/test/data/tokenizer/test4.test
pkgs/html/test/parser_feature_test.dart

Skips unexpected tokens when attempting to find a `StartTagToken` in `dom.dart`, so attribute values can contain the `&` sign without it being part of an actual HTML Entity.
* Issue: https://github.com/dart-lang/tools/issues/2035
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/Extern …

[html] Allow ampersands in attribute values.

---

pkgs/package_config/CHANGELOG.md
pkgs/package_config/pubspec.yaml
pkgs/package_config/test/parse_test.dart

`utf8.encode` has indicated the `Uint8List` since Dart 3.1
Unblock CI where the ignores may not be working in #2040

[package_config] Remove unnecessary casts to Uint8List

---

.github/workflows/markdown.yaml
pkgs/markdown/CHANGELOG.md
pkgs/markdown/example/app.dart
pkgs/markdown/pubspec.yaml

- update package:web references in the example (address some deprecation warnings from package:web)
- fix https://github.com/dart-lang/tools/issues/2024
---
<details>
- Changes to packages require …

[package:markdown] update package:web references in the example

---

pkgs/unified_analytics/lib/src/event.dart

The current docs are inaccurate. In times of yore, it was true that each options file implied a fresh context but not any more so what this count is actually tracking is number of occurences in an options file.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintena …

[unified analytics] fix `lintUsageCount` docs

---

pkgs/bazel_worker/CHANGELOG.md
pkgs/bazel_worker/pubspec.yaml

* Widen protobuf dependency to allow 4.0.0
* Prepare to publish 1.1.3
`package:protobuf` 4.0.0 was released - generated code is backwards compatible but newer generated code (generated using `package:protoc_plugin >=22.0.0`) requires `package:protobuf >= 4.0.0`. 
Widening protobuf dependency allows packages which depend on newer `package:protobuf` to pull it in otherwise it conflicts with the constraint here. (most common complict path is via `package:build_web_compilers`).

Widen protobuf dependency to allow 4.0.0

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/analytics.dart
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/lib/src/user_property.dart
pkgs/unified_analytics/lib/src/utils.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/unified_analytics_test.dart

Reverts to https://github.com/dart-lang/tools/pull/2061 to re-land https://github.com/dart-lang/tools/pull/2007
Also updates the `unified_analytics` package to the next major version (8.0.0) because https://github.com/dart-lang/tools/pull/2007 is a breaking change.

Re-land "[unified_analytics] Send enabled_features as an event parameter rather than a user property (#2007)"

---

pkgs/markdown/test/crash_test.dart

Handle a case where the data could be null
Also type the `getJson` function
Also log a lot more often so the test doesn't seem hanged.

[markdown] fix crash test

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

Flutter is migrating from CocoaPods to Swift Package Manager to manage native dependencies on iOS and macOS. We'd like to answer the following questions:
1. Does the Swift Package Manager feature increase error rates?
2. Can we remove CocoaPods support from Flutter's tooling?
3. Can we tell plugin authors that they can remove CocoaPods integration from their plugins? 
This adds a telemetry event that Flutter will send when it injects plugins into an iOS or macOS project. This will happen whenever a user does commands like `flutter build ios`, `flutter build macos`, and more.
Part of https://github.com/flutter/flutter/issues/147602
Flutter PR: https://github.com/flutter/flutter/pull/166773
cc @vashworth
---
<details>
- See our [contributor …

[UA] Add a Flutter event for plugins injected into an iOS/macOS project.

---

pkgs/code_builder/CHANGELOG.md
pkgs/code_builder/lib/src/specs/expression.dart
pkgs/code_builder/test/specs/code/expression_test.dart

Copied from https://github.com/dart-archive/code_builder/pull/463 through the GitHub UI. I have not run tests locally.
--------------
Opts to rewrite `refer('Foo').newInstanceNamed('', [])` as `Foo` rather than `Foo.`. Two primary reasons
- `Foo.` breaks compilation with bad error messages
- [Analyzer's ConstructorElement#name](https://github.com/dart-lang/sdk/blob/e8939b0ff089a97297cf28626be46c3c75fe72e7/pkg/analyzer/lib/dart/element/element.dart#L466) is a non-nullable String, which pushes the `isEmpty` check to user code
--------------
[x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

Support newInstanceNamed with empty name

---

pkgs/json_rpc_2/CHANGELOG.md
pkgs/json_rpc_2/lib/src/client.dart
pkgs/json_rpc_2/lib/src/peer.dart
pkgs/json_rpc_2/pubspec.yaml
pkgs/json_rpc_2/test/client/client_test.dart
pkgs/json_rpc_2/test/client/utils.dart

This is to support using this package to write a dart analyzer LSP client, which requires String ids.
Also closes https://github.com/dart-lang/tools/issues/738
This is technically breaking because there was some code which tries to coerce string ids back into integers, but this should never have happened. Any server stringifying integer IDs is not spec compliant.
Let me know if we want to release this as non-breaking instead of breaking, I think it would be fine personally, but don't feel strongly either way.

allow custom ID generators in Clients, and support String ids

---

pkgs/coverage/CHANGELOG.md
pkgs/coverage/bin/format_coverage.dart
pkgs/coverage/bin/test_with_coverage.dart
pkgs/coverage/lib/src/coverage_percentage.dart
pkgs/coverage/pubspec.yaml
pkgs/coverage/test/coverage_percentage_test.dart
pkgs/coverage/test/test_with_coverage_package/lib/validate_lib.dart
pkgs/coverage/test/test_with_coverage_package/test/evaluate_test.dart
pkgs/coverage/test/test_with_coverage_test.dart

This pull request introduces a new command-line flag, `--fail-under`, to the `package:coverage` tool. The feature is modeled after the behavior of the `--fail-under` flag in Python’s [`coverage.py`](https://github.com/nedbat/coveragepy) library.
- Accepts a numeric percentage value representing the minimum acceptable code coverage.
- If the actual test coverage falls below this threshold, the tool will return a non-zero exit code (`exit(1)`), signaling failure. 
- An additional `--precision` flag has been introduced to control the number of decimal places shown in the computed coverage percentage.
-Currently i have only added tests for directly testing the coverage percentage calculator,Is it sufficient or should I modify the test_with_coverage_test to test the flag also
Fixes #514

Add --fail-under flag for minimum coverage threshold

---

pkgs/coverage/CHANGELOG.md
pkgs/coverage/lib/src/isolate_paused_listener.dart
pkgs/coverage/pubspec.yaml
pkgs/coverage/test/isolate_paused_listener_test.dart

Another flaky lifecycle error contributing to b/411490560. If the main isolate is resumed while another isolate group's coverage is being collected, the VM service may shut down during collection, causing a "Service connection disposed" error. So we have to keep track of all pending collection requests and wait for them to finish before resuming the main isolate.

[coverage] Fix another flaky lifecycle management error

---

.github/workflows/publish.yaml

Should fix https://github.com/dart-lang/tools/issues/2084

broaden the publish tag regex to allow digits

---

.github/CODEOWNERS
.github/labeler.yml
.github/workflows/process.yaml
pkgs/process/.gitignore
pkgs/process/AUTHORS
pkgs/process/CHANGELOG.md
pkgs/process/LICENSE
pkgs/process/README.md
pkgs/process/dart_test.yaml
pkgs/process/lib/process.dart
pkgs/process/lib/src/interface/common.dart
pkgs/process/lib/src/interface/exceptions.dart
pkgs/process/lib/src/interface/local_process_manager.dart
pkgs/process/lib/src/interface/process_manager.dart
pkgs/process/lib/src/interface/process_wrapper.dart
pkgs/process/pubspec.yaml
pkgs/process/test/src/interface/common_test.dart
pkgs/process/test/src/interface/process_wrapper_test.dart
pkgs/process/test/utils.dart

This moves package:process from the flutter/packages to here. Note that package:process had originally been moved from 
google/process.dart (https://github.com/flutter/packages/pull/5095).
- initial move into this repo
- update the license file and file copyright headers
- update the package + pubspec metadata
- update repo and infra metadata
- update the AUTHORS file (as we're not preserving history from https://github.com/flutter/packages/commits/main/packages/process)
I had tried moving and re-writing the commits using git filter-repo, but it was crashing on one of the signed commits in flutter/packages.
cc @jakemac53  and @stuartmorgan-g for review
---
<details>
- See our [contributor …

Add package:process

---

.github/workflows/test_reflective_loader.yaml
pkgs/test_reflective_loader/CHANGELOG.md
pkgs/test_reflective_loader/lib/test_reflective_loader.dart
pkgs/test_reflective_loader/pubspec.yaml
pkgs/test_reflective_loader/test/location_test.dart

This updates `pkg:test_reflective_loader` to the latest version of `pkg:test` and passes the locations of tests declarations through to `test()` calls.
These locations are then used by `pkg:test` in the JSON reporter so that IDEs can navigate to the correct locations of these tests (rather than always to the `defineReflectiveTests()` call, because the real test declarations are not in the call stack at the point that `test()` is called).
Fixes https://github.com/dart-lang/tools/issues/2081
Fixes https://github.com/Dart-Code/Dart-Code/issues/5480
https://github.com/user-attachments/assets/beef0977-0338-4b86-9850-bbc895aeb09a

[test_reflective_loader] Pass test locations to `pkg:test` to improve IDE navigation

---

.github/workflows/coverage.yaml
pkgs/coverage/CHANGELOG.md
pkgs/coverage/README.md
pkgs/coverage/bin/test_with_coverage.dart
pkgs/coverage/dart_test.yaml
pkgs/coverage/lib/src/collect.dart
pkgs/coverage/lib/src/coverage_options.dart
pkgs/coverage/lib/src/formatter.dart
pkgs/coverage/lib/src/hitmap.dart
pkgs/coverage/lib/src/util.dart
pkgs/coverage/pubspec.yaml
pkgs/coverage/test/collect_coverage_api_test.dart
pkgs/coverage/test/collect_coverage_config_test.dart
pkgs/coverage/test/collect_coverage_test.dart
pkgs/coverage/test/config_file_locator_test.dart
pkgs/coverage/test/function_coverage_test.dart
pkgs/coverage/test/lcov_test.dart
pkgs/coverage/test/run_and_collect_test.dart
pkgs/coverage/test/test_coverage_options/pubspec.yaml
pkgs/coverage/test/test_files/pubspec.yaml
pkgs/coverage/test/test_util.dart
pkgs/coverage/test/test_with_coverage_test.dart
pkgs/coverage/test/util_test.dart
pkgs/coverage/test/workspace_names/pkgs/bar/bar_example/pubspec.yaml
pkgs/coverage/test/workspace_names/pkgs/bar/pubspec.yaml
pkgs/coverage/test/workspace_names/pkgs/foo/foo_example/pubspec.yaml
pkgs/coverage/test/workspace_names/pkgs/foo/pubspec.yaml
pkgs/coverage/test/workspace_names/pubspec.yaml

The eventual goal is that the user should be able to run `dart run coverage:test_with_coverage` from the workspace root, and it runs all the tests in the workspace and produces a single coverage report. There are 2 problems that need to be solved for this to happen:
1) Find and run all the tests (with the correct working directory)
2) Update the scoping logic to not exclude the subpackages from the report
I'm only tackling the scoping changes for now (see [this comment](https://github.com/dart-lang/tools/issues/2083#issuecomment-2892543659)). So this means that users can run `test_with_coverage` from the workspace root, but they have to manually specify the tests they want to run: `dart run coverage:test_with_coverage -- pkgs/foo/test pkgs/bar/test`.
The packages included in the final …

[coverage] Partial workspace support

---

pkgs/coverage/CHANGELOG.md
pkgs/coverage/lib/src/util.dart
pkgs/coverage/pubspec.yaml

package:pubspec_parse depends on package:checked_yaml, which is not available in the Dart SDK repo.

[coverage] Switch from package:pubspec_parse to package:yaml

---

pkgs/source_span/test/multiple_highlight_test.dart

I ported this package to PHP as part of the [scssphp project](https://github.com/scssphp/) (as I'm porting dart-sass which uses this package). When collecting code coverage for the testsuite of my PHP port, I noticed that the code dealing with non-contiguous lines was not covered by the tests.
This PR adds a test covering this case.
---
<details>
- Most changes should add an entry to the …

[source_span] Add a test covering the highlighting of non-contiguous spans

---

pkgs/watcher/CHANGELOG.md
pkgs/watcher/lib/src/directory_watcher/windows.dart
pkgs/watcher/pubspec.yaml
pkgs/watcher/test/directory_watcher/windows_test.dart

Fixes https://github.com/dart-lang/tools/issues/2110

Don't emit two WatchEvents when creating a file in a non-existent directory on Windows

---

pkgs/unified_analytics/CHANGELOG.md
pkgs/unified_analytics/lib/src/constants.dart
pkgs/unified_analytics/lib/src/enums.dart
pkgs/unified_analytics/lib/src/event.dart
pkgs/unified_analytics/pubspec.yaml
pkgs/unified_analytics/test/event_test.dart

This is more a proposal for potential new analytics events than a PR intended to be merged right now.
Specifically, we should consider whether we want a more general purpose event type, or specific events for different MCP server interactions.
For example we do expose runtime errors as both a tool and a resource currently, depending on the client support. Do we want a separate event to capture access to resources, or should we try and make this more general so we can add that kind of event later on without changes to this package?

Add dart mcp server events

---

pkgs/markdown/CHANGELOG.md
pkgs/markdown/lib/src/inline_syntaxes/inline_html_syntax.dart
pkgs/markdown/lib/src/patterns.dart
pkgs/markdown/test/regression_test.dart

See #2119 
Fix performance and correctness of HTML comment parser.
RegExp had catastrophic backtracking. Also didn't match the spec if linked to.
(Which is still CM 30, not 31.2, they differ.)
Fixed a few other incorrect parsings.
- The content of `<?...?>`, `<!a...>` and `<![CDATA[...]]>` can
contain newlines. Changed `.` to `[^]`.
- The `<![CDATA[` tag is case sensitive. Changed RegExp to be
case sensitive, so added `A-Z` to all the `a-z`s used in that
regexp.

[Markdown] Fix HTML comment parser.

---

pkgs/code_builder/CHANGELOG.md
pkgs/code_builder/lib/src/emitter.dart
pkgs/code_builder/test/specs/field_test.dart

Closes #2118 
This PR fixes the order of the `external` and `static` keywords in fields to follow correct Dart language structure.
Fields in `code_builder` should now render as `external static` rather than `static external` when both are `true`.
---
<details>
<summary>Contribution guidelines</summary><br>
</details>

[code_builder] Set `external` and `static` in correct order

---

.gemini/config.yaml
.gemini/styleguide.md

To be merged after installing Gemini Code Review.
cc @athomas 
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing) …

Configure Gemini code review

---

pkgs/code_builder/CHANGELOG.md
pkgs/code_builder/lib/src/emitter.dart
pkgs/code_builder/test/specs/enum_test.dart

Closes #1143
The `class` emitter already used `writeln` following a `=>` method to
include blank lines between members. Make this consistent for enums,
extensions, and mixins. Extract a method and use it for each type.
Sort changelog with user-facing changes at the top.

Consistent blank after => members in class-likes

---

pkgs/watcher/CHANGELOG.md
pkgs/watcher/lib/src/directory_watcher.dart
pkgs/watcher/lib/src/directory_watcher/windows.dart
pkgs/watcher/pubspec.yaml
pkgs/watcher/test/directory_watcher/windows_test.dart

For #2152.
Update CHANGELOG + pubspec for release for the two fixes.

List directory failure

---

pkgs/test_reflective_loader/CHANGELOG.md
pkgs/test_reflective_loader/lib/test_reflective_loader.dart
pkgs/test_reflective_loader/pubspec.yaml
pkgs/test_reflective_loader/test/location_test.dart
pkgs/test_reflective_loader/test/test_reflective_loader_test.dart

if a test class defines `setUpClass` it will be run before any tests are ever run. if it is asynchronous then no test runs until the future is completed
`tearDownClass` is called once after all tests are run
~the same `InstanceMirror` is used for the setup and for the tear-down, following how setup and tear-down is done for each unit test~
tests are updated to support and check for new behavior

add support for `setUpClass` and `tearDownClass`

---

pkgs/watcher/test/file_watcher/file_tests.dart
pkgs/watcher/test/file_watcher/native_test.dart
pkgs/watcher/test/file_watcher/polling_test.dart
pkgs/watcher/test/file_watcher/startup_race_tests.dart
pkgs/watcher/test/utils.dart

For #2170, start adding test coverage.
I initially started adding test coverage around symlinks, but encountered two existing issues that made it awkward
- there is a race on startup on MacOS that means there might be events from before the watch; the existing tests are flaky because of this issue
- the file watchers have inconsistent behavior if the file watched does not exist
Cover both of these with tests before making any changes :)
Add `expectNoEvents` and use it in one existing test as it's more readable than triggering then waiting for a different event.

Add test coverage around startup race and missing file on startup.

---

pkgs/watcher/CHANGELOG.md
pkgs/watcher/pubspec.yaml

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a- …

Prepare to release watcher 1.1.4

---

pkgs/markdown/CHANGELOG.md
pkgs/markdown/lib/src/block_syntaxes/list_syntax.dart
pkgs/markdown/test/original/unordered_lists.unit

This PR is aimed to solve the issue, described there https://github.com/dart-lang/tools/issues/2172.

Fixing structure issue of nested lists indented by tabs (#2172)

---

pkgs/watcher/CHANGELOG.md
pkgs/watcher/lib/src/file_watcher/native.dart
pkgs/watcher/pubspec.yaml
pkgs/watcher/test/file_watcher/startup_race_tests.dart

On MacOS `File.watch` can report events from slightly before the watch is created.
The startup race is annoying for testing, since tests very often create a file then immediately create a watcher.
It also doesn't seem useful to users, and it's inconsistent with other platforms.
So, fix it :)

Fix file watcher startup race on MacOS

---

pkgs/watcher/test/file_watcher/link_tests.dart
pkgs/watcher/test/utils.dart

For #2170, cover file watcher behavior with symlinks in tests.

Add test coverage for file watcher and symlinks.

---

pkgs/watcher/lib/src/directory_watcher/linux.dart
pkgs/watcher/lib/src/directory_watcher/mac_os.dart
pkgs/watcher/lib/src/event.dart
pkgs/watcher/lib/src/file_watcher/native.dart
pkgs/watcher/lib/src/utils.dart

Use the new `Event` extension type that makes it clear that delete events don't set `isDirectory`.
Simplify `_canonicalEvent`, removes don't specify isDirectory so those always conflict, it's only file add and file modify that can be reduced to a single "create" event.
MacOS watcher never receives move events or "modify directory" events from the OS, make this clear: assert(false) and drop the event if such an event is received, so tests will catch it and if it happens in the wild we use the code tested with no such events.
Clean up MacOS watcher _sortEvents because it can't receive directory move or "modify directory".
No behavior changes.
Test failures on MacOS on dev SDK are unrelated, they are due to an SDK issue https://github.com/dart-lang/sdk/issues/61693

Use Event extension type for MacOS DirectoryWatcher.
