dart-lang/tools

pkgs/dash_analytics/analysis_options.yaml, pkgs/dash_analytics/example/dash_analytics_example.dart, pkgs/dash_analytics/lib/src/analytics.dart, pkgs/dash_analytics/lib/src/enums.dart, pkgs/dash_analytics/test/dash_analytics_test.dart
Using this event to test that we are saving to the locally persisted log file
=> [pkgs/dash_analytics] Adding event for analyzer startup

README.md, pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/README.md, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/pubspec.yaml
- rev to 0.1.0
- update various markdown badges (now that we have a published version)
=> rev to 0.1.0

pkgs/unified_analytics/lib/src/constants.dart
=> Revert "Update messaging for tools messaging"

pkgs/unified_analytics/lib/src/constants.dart
Relanding https://github.com/dart-lang/tools/pull/32
Didn't include better messaging
=> Messaging update; second attempt after revert

pkgs/unified_analytics/USAGE_GUIDE.md, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/test/unified_analytics_test.dart
Adding the credentials to point to test Google Analytics for local development + tests to ensure credentials have not been changed
=> Add dev credentials for google analytics

pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/example/unified_analytics_example.dart, pkgs/unified_analytics/lib/src/analytics.dart, pkgs/unified_analytics/lib/src/config_handler.dart, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/lib/src/enums.dart, pkgs/unified_analytics/pubspec.yaml, pkgs/unified_analytics/test/unified_analytics_test.dart, pkgs/unified_analytics/test/workflow_test.dart
This will break all clients (without the changes I have in progress locally in the SDK, will break it too).  So update major version number.
I am hoping that it is valid to have dashes in the tool name as the PDD specifies them with dashes, so added that to the regexp.
@keertip
=> Change supported tools list to align with PDD

pkgs/unified_analytics/lib/src/session.dart
Using recommended approach for error handling
=> Update session file error handling to catch file missing

pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/pubspec.yaml
=> Bump version to `1.0.0`

pkgs/unified_analytics/lib/src/analytics.dart, pkgs/unified_analytics/lib/src/ga_client.dart, pkgs/unified_analytics/lib/unified_analytics.dart, pkgs/unified_analytics/test/no_op_analytics_test.dart
Fixes https://github.com/dart-lang/tools/issues/76
=> [unified_analytics] Add NoOpAnalytics

pkgs/unified_analytics/lib/src/enums.dart
To contribute to https://dart-review.googlesource.com/c/sdk/+/300862
=> Add memory events.

.github/workflows/no-response.yml, .github/workflows/publish.yaml, .github/workflows/pull_request_label.yml
This PR contains changes created by the blast repo tool.
- `auto-publish`
- `github-actions`
- `no-response`
=> blast repo changes: auto-publish, github-actions, no-response

.github/workflows/graphs.yml, pkgs/graphs/CHANGELOG.md, pkgs/graphs/analysis_options.yaml, pkgs/graphs/pubspec.yaml, pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/analysis_options.yaml, pkgs/unified_analytics/example/unified_analytics_example.dart, pkgs/unified_analytics/lib/src/analytics.dart, pkgs/unified_analytics/lib/src/asserts.dart, pkgs/unified_analytics/lib/src/config_handler.dart, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/lib/src/ga_client.dart, pkgs/unified_analytics/lib/src/initializer.dart, pkgs/unified_analytics/lib/src/log_handler.dart, pkgs/unified_analytics/lib/src/session.dart, pkgs/unified_analytics/lib/src/utils.dart, pkgs/unified_analytics/pubspec.yaml, pkgs/unified_analytics/test/asserts_test.dart, pkgs/unified_analytics/test/legacy_analytics_test.dart, pkgs/unified_analytics/test/no_op_analytics_test.dart, pkgs/unified_analytics/test/unified_analytics_test.dart, pkgs/unified_analytics/test/workflow_test.dart
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
- …
=> Merge master updates into feature branch

pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/lib/src/enums.dart, pkgs/unified_analytics/pubspec.yaml
Bumping version to `3.0.0`
---
<details>
Note that many Dart repos have a weekly …
=> Bump versions to publish

pkgs/unified_analytics/example/sample_rate.dart, pkgs/unified_analytics/lib/src/utils.dart
Reference umbrella tracker:
Including an example file that demonstrates how the sampling rate will work for real surveys.
For this to work well in practice, we will need to ensure that each survey's metadata json file has a `uniqueId` field that is generated using a UUID generator, preferably using the one found in `lib/src/utils.dart` for this package.
---
<details>
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and …
=> Sample rate example added

.github/labeler.yml, .github/workflows/extension_discovery.yml, pkgs/extension_discovery/CHANGELOG.md, pkgs/extension_discovery/README.md, pkgs/extension_discovery/analysis_options.yaml, pkgs/extension_discovery/pubspec.yaml, pkgs/extension_discovery/test/find_extensions_test.dart
- add a ci for package:extension_discovery
- update the readme to include std markdown badges
---
<details> …
=> add CI; update readme

.github/workflows/cli_config.yml, .github/workflows/extension_discovery.yml, .github/workflows/graphs.yml, .github/workflows/unified_analytics.yml
- validate a prerelease setup-dart version
Testing a pre-release setup-dart action version (as per https://github.com/dart-lang/setup-dart/wiki/Publishing-procedure).
---
<details>
- Changes to packages require …
=> validate a pre-release setup-dart action

.github/ISSUE_TEMPLATE/extension_discovery.md, .github/ISSUE_TEMPLATE/graphs.md, .github/labeler.yml, .github/workflows/graphs.yml, README.md
- misc infra updates for dart-lang/tools
---
<details>
Note that many Dart repos have a …
=> misc infra updates for dart-lang/tools

pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/example/sample_rate.dart, pkgs/unified_analytics/lib/src/analytics.dart, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/lib/src/event.dart, pkgs/unified_analytics/lib/src/ga_client.dart, pkgs/unified_analytics/lib/src/log_handler.dart, pkgs/unified_analytics/lib/src/session.dart, pkgs/unified_analytics/lib/src/survey_handler.dart, pkgs/unified_analytics/lib/src/user_property.dart, pkgs/unified_analytics/pubspec.yaml, pkgs/unified_analytics/test/no_op_analytics_test.dart, pkgs/unified_analytics/test/unified_analytics_test.dart
- update to the latest `package:dart_flutter_team_lints`
---
<details>
Note that many …
=> update to the latest package:dart_flutter_team_lints

.github/ISSUE_TEMPLATE/unified_analytics_event.yml, .github/ISSUE_TEMPLATE/unified_analytics_user_property.yml, pkgs/unified_analytics/USAGE_GUIDE.md
This PR adds two new issue templates for the unified analytics package. It also adds a new section to the usage guide.
=> Adding new issue templates

.github/ISSUE_TEMPLATE/unified_analytics.md, .github/ISSUE_TEMPLATE/unified_analytics_event.yml, .github/ISSUE_TEMPLATE/unified_analytics_user_property.yml
Fixes https://github.com/dart-lang/tools/issues/190
=> Fixing titles of issue templates

pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/lib/src/analytics.dart, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/pubspec.yaml, pkgs/unified_analytics/test/unified_analytics_test.dart
Fixes:
- https://github.com/dart-lang/tools/issues/213
---
<details>
Note that many …
=> Fix consent message formatting

pkgs/unified_analytics/USAGE_GUIDE.md
Fixes the guide to be in line with the current state
---
<details>
Note that many Dart …
=> Update USAGE_GUIDE to update the `flutterChannelCount` key in `LogFileStats`

pkgs/graphs/analysis_options.yaml
Addresses: https://github.com/dart-lang/tools/actions/runs/7235083619/job/19712137639
=> [graphs] Clean up lints for Dart 3.3

pkgs/cli_config/CHANGELOG.md, pkgs/cli_config/README.md, pkgs/cli_config/example/bin/cli_config_example.dart, pkgs/cli_config/lib/src/config.dart, pkgs/cli_config/pubspec.yaml, pkgs/cli_config/test/cli_config_test.dart
To enable a sync method in downstream packages.
=> [cli_config] Introduce sync method

pkgs/graphs/CHANGELOG.md, pkgs/graphs/pubspec.yaml
- rev to 2.3.2 in prep for publishing
---
<details>
Note that many Dart …
=> rev to 2.3.2 in prep for publishing

pkgs/source_map_stack_trace/CHANGELOG.md, pkgs/source_map_stack_trace/pubspec.yaml
To finalize the move to this new repository.
---
<details>
Note that many …
=> Publish new version of `package:source_map_stack_trace`

pkgs/source_map_stack_trace/README.md
.
---
<details>
Note that many Dart repos have a weekly cadence for …
=> Fix badge ref for `package:source_map_stack_trace`.

README.md, pkgs/coverage/CHANGELOG.md, pkgs/coverage/pubspec.yaml
.
---
<details>
Note that many Dart repos have a weekly cadence for …
=> Sort `README.md` and add package:coverage

pkgs/unified_analytics/CHANGELOG.md, pkgs/unified_analytics/lib/src/constants.dart, pkgs/unified_analytics/lib/src/event.dart, pkgs/unified_analytics/pubspec.yaml, pkgs/unified_analytics/test/event_test.dart
Work towards https://github.com/flutter/devtools/issues/7856.
=> Added a couple parameters to `Event.devtoolsEvent` and `Event.exception`

.github/workflows/stream_transform.yaml, pkgs/stream_transform/CHANGELOG.md, pkgs/stream_transform/example/main.dart, pkgs/stream_transform/pubspec.yaml
Fixes a deprecation warning from the latest SDK.
=> update stream_transform example to package:web

.github/workflows/markdown_crash_test.yaml, .github/workflows/markdown_flutter.yaml
Also run the crash tests whenever changes to that file are made, or on demand.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBU …
=> Fix markdown workflow names

.github/workflows/deploy_pages.yaml
- fix the deploy_pages.yaml workflow
---
<details>
Note that many Dart …
=> fix the deploy_pages.yaml workflow

pkgs/benchmark_harness/pubspec.yaml, pkgs/io/pubspec.yaml, pkgs/markdown/pubspec.yaml, pkgs/mime/pubspec.yaml, pkgs/package_config/pubspec.yaml, pkgs/pool/pubspec.yaml, pkgs/pub_semver/pubspec.yaml, pkgs/pubspec_parse/pubspec.yaml, pkgs/source_maps/pubspec.yaml, pkgs/source_span/pubspec.yaml, pkgs/sse/pubspec.yaml, pkgs/stack_trace/pubspec.yaml, pkgs/stream_channel/pubspec.yaml, pkgs/stream_transform/pubspec.yaml, pkgs/string_scanner/pubspec.yaml, pkgs/term_glyph/pubspec.yaml, pkgs/test_reflective_loader/pubspec.yaml, pkgs/timing/pubspec.yaml, pkgs/watcher/pubspec.yaml, pkgs/yaml/pubspec.yaml, pkgs/yaml_edit/pubspec.yaml
- add issue_tracker links to pubspec files
- correct the pubspec indents for several packages
---
<details> …
=> add issue_tracker links to pubspec files

.github/CODEOWNERS, CODEOWNERS
Apparently, the format for a team is org/team..
Also delete old `CODEOWNERS` file
---
<details> …
=> Fix CODEOWNERS

.github/labeler.yml, README.md, pkgs/process/CHANGELOG.md, pkgs/process/analysis_options.yaml, pkgs/process/pubspec.yaml
- have package:lints use package:lints/recommended
---
<details>
Note that …
=> have package:lints use package:lints/recommended

.github/ISSUE_TEMPLATE/process.md
- add an issue template for package:process
I forgot this bit of the move; cc @jakemac53.
---
<details> …
=> add an issue template for package:process

pkgs/extension_discovery/test/find_extensions_test.dart
- disable failing test
- related to https://github.com/dart-lang/tools/issues/2134
---
<details> …
=> disable failing test

pkgs/pool/CHANGELOG.md, pkgs/pool/pubspec.yaml
- rev package:pool in prep for publishing
- fix https://github.com/dart-lang/tools/issues/2109
---
<details> …
=> rev package:pool in prep for publishing

pkgs/mime/doc/media_types.md, pkgs/mime/tool/media_types.dart
- some minor refactoring of the media types golden table to make it a little easier to understand what changes a diff implies
---
<details> …
=> refactor the media types golden table
